{
 "title": "Humantree",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"backend\"} |= ``"
    }
   ]
  },
  {
   "title": "Erreur",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Test error 4XX/5XX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{status=~\"4..\"}[5m])) by (handler)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) by (handler)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate limits hit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 8, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(rate_limit_exceeded_total[5m])) by (path)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Activité", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection à la DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 10 },
   "targets": [
    { "expr": "db_pool_checked_out", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence p95",
   "type": "timeseries",
   "description": "Test vitesse réponse de l'api",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requête en cours",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sum(http_requests_inprogress)", "legendFormat": "__auto" }
   ]
  }
 ]
}