"""add_index_skill_id

Revision ID: 0eb3c3ad1adf
Revises: f3454e19aaa0
Create Date: 2026-02-20 07:39:21.740264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb3c3ad1adf'
down_revision: Union[str, Sequence[str], None] = 'f3454e19aaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_check_skill_skill_id', 'user_check_skill', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_check_skill_skill_id', table_name='user_check_skill')
    # ### end Alembic commands ###
