"""remove_skill_tree_copy_fields

Revision ID: 15f420886d94
Revises: d1cf75c64b44
Create Date: 2026-02-26 13:57:47.676736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f420886d94'
down_revision: Union[str, Sequence[str], None] = 'd1cf75c64b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('skill_trees_copied_from_id_fkey'), 'skill_trees', type_='foreignkey')
    op.drop_column('skill_trees', 'is_copy')
    op.drop_column('skill_trees', 'copied_from_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_trees', sa.Column('copied_from_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('skill_trees', sa.Column('is_copy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('skill_trees_copied_from_id_fkey'), 'skill_trees', 'skill_trees', ['copied_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
