"""create is_root in skills

Revision ID: 1a0bb81ffcc7
Revises: cc59ee5953f7
Create Date: 2026-02-09 00:50:21.934838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0bb81ffcc7'
down_revision: Union[str, Sequence[str], None] = 'cc59ee5953f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('is_root', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'is_root')
    # ### end Alembic commands ###
