"""initial_create_table

Revision ID: 1eed41c5a467
Revises:
Create Date: 2026-02-17 05:13:31.539866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1eed41c5a467"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "skill_trees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("creator_username", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_username"], ["users.username"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("skill_tree_id", sa.Integer(), nullable=False),
        sa.Column("is_root", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["skill_tree_id"], ["skill_trees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "skill_tree_id", name="skills_name_skill_tree_id_key"
        ),
    )
    op.create_index(
        "idx_skills_skill_tree_id", "skills", ["skill_tree_id"], unique=False
    )
    op.create_index(
        "unique_tree_skill_id_root",
        "skills",
        ["skill_tree_id", "id"],
        unique=True,
        postgresql_where=sa.text("is_root = true"),
    )
    op.create_table(
        "skill_dependencies",
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("unlock_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("skill_id != unlock_id", name="skill_dependencies_check"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unlock_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("skill_id", "unlock_id"),
    )
    op.create_table(
        "user_check_skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=True),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "skill_id", name="user_check_skill_user_id_skill_id_key"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_check_skill")
    op.drop_table("skill_dependencies")
    op.drop_index(
        "unique_tree_skill_id_root",
        table_name="skills",
        postgresql_where=sa.text("is_root = true"),
    )
    op.drop_index("idx_skills_skill_tree_id", table_name="skills")
    op.drop_table("skills")
    op.drop_table("skill_trees")
    op.drop_table("users")
    # ### end Alembic commands ###
