"""add favorite table

Revision ID: 29087e854c05
Revises: b8809bb058e1
Create Date: 2026-02-18 07:21:38.921621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29087e854c05'
down_revision: Union[str, Sequence[str], None] = 'b8809bb058e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_trees',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_tree_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['skill_tree_id'], ['skill_trees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_tree_id', name='user_favorite_trees_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_trees')
    # ### end Alembic commands ###
