"""create creator in skill_tree

Revision ID: 3494a0de6438
Revises: ce76849852ce
Create Date: 2026-02-10 21:55:08.812258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3494a0de6438"
down_revision: Union[str, Sequence[str], None] = "ce76849852ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skill_trees",
        sa.Column(
            "creator_username",
            sa.String(length=30),
            nullable=False,
            server_default="admin",
        ),
    )  # avec admin en par défaut
    op.create_foreign_key(
        None,
        "skill_trees",
        "users",
        ["creator_username"],
        ["username"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "skill_trees", type_="foreignkey")
    op.drop_column("skill_trees", "creator_username")
    # ### end Alembic commands ###
