"""add_skill_linked_tree_id

Revision ID: 434f7d1aaab3
Revises: 4bc8a334de19
Create Date: 2026-02-26 12:47:21.642977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434f7d1aaab3'
down_revision: Union[str, Sequence[str], None] = '4bc8a334de19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('linked_tree_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skills', 'skill_trees', ['linked_tree_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'linked_tree_id')
    # ### end Alembic commands ###
