"""add tokens table

Revision ID: b34b319bbb96
Revises: 29087e854c05
Create Date: 2026-02-20 05:47:22.675734

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b34b319bbb96"
down_revision: str | Sequence[str] | None = "29087e854c05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
