"""add new index where he test if root is unique for a tree

Revision ID: ce76849852ce
Revises: 1a0bb81ffcc7
Create Date: 2026-02-09 00:53:26.057518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce76849852ce'
down_revision: Union[str, Sequence[str], None] = '1a0bb81ffcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_tree_skill_id_root', 'skills', ['skill_tree_id', 'id'], unique=True, postgresql_where=sa.text('is_root = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_tree_skill_id_root', table_name='skills', postgresql_where=sa.text('is_root = true'))
    # ### end Alembic commands ###
