"""add_skill_tree_copy_fields

Revision ID: d1cf75c64b44
Revises: 434f7d1aaab3
Create Date: 2026-02-26 13:01:19.122202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cf75c64b44'
down_revision: Union[str, Sequence[str], None] = '434f7d1aaab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_trees', sa.Column('is_copy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('skill_trees', sa.Column('copied_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill_trees', 'skill_trees', ['copied_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill_trees', type_='foreignkey')
    op.drop_column('skill_trees', 'copied_from_id')
    op.drop_column('skill_trees', 'is_copy')
    # ### end Alembic commands ###
