# --- AI / LLM ---
MODEL_ANTHROPIC = "claude-haiku-4-5-20251001"
MODEL_OPENAI = "gpt-4o-mini"
MODEL_GOOGLE = "gemini-2.0-flash"

PROVIDER_ANTHROPIC = "anthropic"
PROVIDER_OPENAI = "openai"
PROVIDER_GOOGLE = "google"

PROVIDER_MODELS = {
    PROVIDER_ANTHROPIC: MODEL_ANTHROPIC,
    PROVIDER_OPENAI: MODEL_OPENAI,
    PROVIDER_GOOGLE: MODEL_GOOGLE,
}

MAX_TOKENS_GENERATE = 4096
MAX_TOKENS_ENRICH = 2048
MAX_TOKENS_EVALUATE = 1024

# --- Agent orchestrator ---
AGENT_QUALITY_THRESHOLD = 0.7
AGENT_MAX_ATTEMPTS = 2
AGENT_TIMEOUT_BUDGET = 90.0

# --- Embeddings ---
EMBEDDING_MODEL = "intfloat/multilingual-e5-small"
EMBEDDING_DIMENSIONS = 384
EMBEDDING_BATCH_SIZE = 50  # pour le backfill

# --- Auth / Cookies ---
ACCESS_TOKEN_MAX_AGE = 900  # 15 minutes
REFRESH_TOKEN_MAX_AGE = 7 * 24 * 60 * 60  # 7 jours
COOKIE_SAMESITE = "strict"
